title: Amazing Truth Bible School Dev Blog
author: Aaron Jones
  name: bigboss424
  email: ajones061392@yahoo.com
description: > # this means to ignore newlines until "show_excerpts:"
 This blog is to help me keep track and updated on the development of
 Amazing Truth Bible School the website. As I learn how to implement and
 integrate Firebase and learn to use Angular to build PWAs in order to 
 deliver the content from the site forward.             

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: devto,          user_url: "https://dev.to/jekyll" }
    - { platform: dribbble,       user_url: "#" }
    - { platform: facebook,       user_url: "#" }
    - { platform: flickr,         user_url: "#" }
    - { platform: github,         user_url: "https://github.com/bigboss424" }
    - { platform: google_scholar, user_url: "#" }
    - { platform: instagram,      user_url: "#" }
    - { platform: keybase,        user_url: "#" }
    - { platform: linkedin,       user_url: "#" }
    - { platform: microdotblog,   user_url: "#" }
    - { platform: pinterest,      user_url: "#" }
    - { platform: stackoverflow,  user_url: "#" }
    - { platform: telegram,       user_url: "#" }
    - { platform: twitter,        user_url: "#" }
    - { platform: youtube,        user_url: "#" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
